[package]
name = "nom-exif"
version = "1.3.0"
edition = "2021"
license-file = "LICENSE"
description = "Exif/metadata parsing library written in pure Rust, both JPEG/HEIF/HEIC images and MOV/MP4 videos are supported."
homepage = "https://github.com/mindeng/nom-exif"
repository = "https://github.com/mindeng/nom-exif"
exclude = [
    "testdata/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
regex = { version = "1.10" }
chrono = "0.4"
tracing = {version = "0.1.40", optional = true}

[features]
default = []
json_dump = ["serde"]
tracing = ["dep:tracing"]

[dev-dependencies]
test-case = "3"
rand = "0.8"
chrono = "0.4"
serde_json = "1.0"
regex = { version = "1.10" }
clap = { version = "4.4", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[[example]]
name = "rexiftool"
# required-features = ["json_dump"]

[workspace]
members = [".", "afl-fuzz"]
